### PR TITLE
[RFC] Only run a subset of testcases in separated processes

### PR DESCRIPTION
**Pull request by dottedmag**
This is quite a crude implementation that works, so RFC.

### CODE REVIEW

**Comment by dottedmag** [comment]
Hi.

I have updated the patch: rebased and added unittest.TestCase case to the README.md

**Comment by dottedmag** [comment]
*ping*

**Comment by dmccombs** [comment]
Thanks Mikhail. Sorry I haven't had time to play with this yet. I may have time today, if not hopefully this coming week.

**Comment by dottedmag** [comment]
Cool, thank you.

**Comment by dmccombs** [comment]
New version with this change (0.6) is released and available on PyPI.

**Pull request merged**
